### ISSUE TITLE
Cannot compute the metrics

### ISSUE THREAD

**Issue by stevaras2** [allenai/SciRIFF#1]
I followed the instructions in the README.md file on how to install the repository correctly and it seems it works. I generated some examples for all the task using the scitulu-7B model using the following command
```
python script/eval/predict_eleuther.py \
  --model vllm \
  --model_name allenai/scitulu-7b \
  --chat_template tulu \
  --gpus 1 \
  --tasks science_adapt \
  --result_base results/predictions \
  --limit 10
```
The results are stored in the __results/predictions/scitulu-7b/science_adapt/eleuther.jsonl/allenai__scitulu-7b/__ folder. In detail, the  files generated by the above command are the following
![image](https://github.com/allenai/SciRIFF/assets/20558565/a421c75c-1cca-4b52-8be1-2a7c214b87f0)
Till this point, everything properly works. However, when I tried to compute the scores as suggested in the README.md I get some errors. In detail, I tried plenty of commands in order to make it work, but it was not possible. The following two commands and their corresponding errors can summarize all the problems I faced in the computation of the evaluation metrics.

Command 1
```
 python script/eval/compute_science_metrics.py   --pred_dir results/predictions/scitulu-7b/science_adapt/eleuther.jsonl/   --metrics_dir results/metrics
```
Error 1
```
Traceback (most recent call last):
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 258, in <module>
    main()
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 254, in main
    se.run_eval()
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 205, in run_eval
    self.eval_one_model(model_dir)
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 138, in eval_one_model
    if not [fname for fname in pred_dir.iterdir()]:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 138, in <listcomp>
    if not [fname for fname in pred_dir.iterdir()]:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sstefanidis/.conda/envs/sciriff/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: 'results/predictions/scitulu-7b/science_adapt/eleuther.jsonl/allenai__scitulu-7b/samples_mup_single_document_summarization_2024-06-25T11-40-40.294383.jsonl'
```

Command 2
```
python script/eval/compute_science_metrics.py   --pred_dir results/predictions/   --metrics_dir results/metrics
```

Error 2
```
Traceback (most recent call last):
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 258, in <module>
    main()
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 254, in main
    se.run_eval()
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 208, in run_eval
    self.make_summary_table(self.metrics_summary)
  File "/home/sstefanidis/rnd-sciriff/script/eval/compute_science_metrics.py", line 65, in make_summary_table
    pvt = tbl.pivot_table(index="model", columns=["task", "metric"], values="value")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sstefanidis/.conda/envs/sciriff/lib/python3.11/site-packages/pandas/core/frame.py", line 9509, in pivot_table
    return pivot_table(
           ^^^^^^^^^^^^
  File "/home/sstefanidis/.conda/envs/sciriff/lib/python3.11/site-packages/pandas/core/reshape/pivot.py", line 102, in pivot_table
    table = __internal_pivot_table(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sstefanidis/.conda/envs/sciriff/lib/python3.11/site-packages/pandas/core/reshape/pivot.py", line 148, in __internal_pivot_table
    raise KeyError(i)
KeyError: 'value'
```

As I understand both errors, root from the inability of the script to allocate the correct generation files.
If you have an idea why this happens please let me know.

**Comment by stevaras2** [comment]
Is there any update?

**Comment by dwadden** [comment]
Just took a look. Command 1 isn't expected to work, but command 2 matches the directions in the [README](https://github.com/allenai/SciRIFF/blob/main/README.md#computing-metrics) and should work. It also seems to work fine when I run it on my machine.
Looks like the error is happening right at the end when the model tries to collect results into a summary. A few things:

- Can you confirm that you've followed the setup instructions in the `README` to install all dependencies?
- If so, feel free to create a `zip` file of the full `results` directory as it stands for you and I can try to reproduce the error.

**Comment by e-tornike** [comment]
I had the same issue (due to a difference in how the output folders are nested), but it got resolved after installing the following commit for the Eleuther harness (as recommended by the authors):

```bash
git clone https://github.com/EleutherAI/lm-evaluation-harness.git
cd lm-evaluation-harness
git checkout e74ec96
pip install -e .[vllm]
```

**Comment by dwadden** [comment]
Ah thanks for this. Yes, things will break if you don't use exactly the right version... it's a bit finicky.
